
export const commandConfig = {
    "lock": {
      commandAlias: "lock",
      commandType:'lock',
      value: [0x01, 0x01, 0x00],
      hexTag:"01",  //通过云端控车的指令tag
      hexValue:"00",  //通过云端控车的指令value
      mark: "上锁",
      toastSuccess:"闭锁成功",
      toastFail:"闭锁失败",
      minWaitingTime: 2000,
      maxWaitingTime: 5000,
      needCarData: true,
      voiceName: "lock.mp3",
      vehicleConditionData_key:'lock',
      vehicleConditionData_val:1
    },
    "unlock": {
      commandAlias: "",
      commandType:'lock',
      value: [0x01, 0x01, 0x01],
      hexTag:"01",
      hexValue:"01",
      mark: "解锁",
      toastSuccess:"解锁成功",
      toastFail:"解锁失败",
      minWaitingTime: 2000,
      maxWaitingTime: 5000,
      needCarData: true,
      voiceName: "unlock.mp3",
      vehicleConditionData_key:'lock',
      vehicleConditionData_val:0
    },
    "closeWindow": {
      commandAlias: "closeWindow",
      commandType:'window',
      value: [0x02, 0x01, 0x00],
      hexTag:"02",
      hexValue:"00",
      minWaitingTime: 8000,
      maxWaitingTime: 9000,
      mark: "关窗",
      toastSuccess:"车窗已关闭",
      toastFail:"",
      needCarData: true,
      voiceName: "windowClose.mp3",
      vehicleConditionData_key:'window',
      vehicleConditionData_val:0
    },
    "openWindow": {
      commandAlias: "openWindow",
      commandType:'window',
      value: [0x02, 0x01, 0x01],
      hexTag:"02",
      hexValue:"01",
      minWaitingTime: 8000,
      maxWaitingTime: 9000,
      mark: "开窗",
      toastSuccess:"车窗已开启",
      toastFail:"",
      needCarData: true,
      voiceName: "windowOpen.mp3",
      vehicleConditionData_key:'window',
      vehicleConditionData_val:1
    },
    "search": {
      commandAlias: "",
      commandType:'search',
      value: [0x04, 0x01, 0x01],
      hexTag:"04",
      hexValue:"01",
      mark: "寻车",
      toastSuccess:"",
      toastFail:"",
      minWaitingTime: 2000,
      maxWaitingTime: 4000,
      needCarData: false,
      voiceName: "lookCar.mp3",
      vehicleConditionData_key:null,
      vehicleConditionData_val:null
    },
    "closeTrunk": {
      commandAlias: "closeTrunk",
      commandType:'trunk',
      value: [0x06, 0x01, 0x00],
      hexTag:"06",
      hexValue:"00",
      minWaitingTime: 8000,
      maxWaitingTime: 12000,
      mark: "关闭后备箱",
      toastSuccess:"尾门已关闭",
      toastFail:"",
      needCarData: true,
      voiceName: "trunckClose.mp3",
      vehicleConditionData_key:'trunk',
      vehicleConditionData_val:0
    },
    "openTrunk": {
      commandAlias: "openTrunk",
      commandType:'trunk',
      value: [0x06, 0x01, 0x01],
      hexTag:"06",
      hexValue:"01",
      minWaitingTime: 2000,
      maxWaitingTime: 15000,
      mark: "打开后备箱",
      toastSuccess:"尾门已开启",
      toastFail:"",
      needCarData: true,
      voiceName: "trunckOpen.mp3",
      vehicleConditionData_key:'trunk',
      vehicleConditionData_val:1
    },
    "stopEngine": {
      commandAlias: "stopEngine",
      commandType:'engine',
      hexTag:"08",
      hexValue:"00",
      value: [0x08, 0x01, 0x00],
      minWaitingTime: 2000,
      maxWaitingTime: 5000,
      mark: "熄火",
      toastSuccess:"引擎已熄火",
      toastFail:"",
      needCarData: true,
      voiceName: "end.mp3",
      vehicleConditionData_key:'isStart',
      vehicleConditionData_val:false
    },
    "startEngine": {
      commandAlias: "startEngine",
      commandType:'engine',
      value: [0x08, 0x01, 0x01],
      hexTag:"08",
      hexValue:"01",
      minWaitingTime: 2000,
      maxWaitingTime: 5000,
      mark: "启动",
      toastSuccess:"引擎已启动",
      toastFail:"",
      needCarData: true,
      voiceName: "start.mp3",
      vehicleConditionData_key:'isStart',
      vehicleConditionData_val:true
    },
    "refrush": {
      commandAlias: "refrush",
      value: [0x01, 0x01, 0x00],
      hexTag:"",
      hexValue:"",
      minWaitingTime: 1000,
      maxWaitingTime: 5000,
      mark: "刷新",
      toastSuccess:"",
      toastFail:"",
      needCarData: false,
      voiceName: null,
      vehicleConditionData_key:null,
      vehicleConditionData_val:null
    }
  };

export const cmdCodes = {
    '200': '执行成功',
    '301': '用户未登录',
    '302': '正在执行车控，不可再次执行',
    '303': '未连接车辆',
    '304': '车控命令不支持',
    '404': '车况情况不允许执行', //（本地模式/当前车控前置车况不满足等）
    '501': '车况执行超时'
}